[[override]]
  name = "k8s.io/api"
  revision = "2d6f90ab1293a1fb871cf149423ebb72aa7423aa"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "103fd098999dc9c0c88536f5c9ad2e5da39373ae"

[[override]]
  name = "k8s.io/client-go"
  revision = "1f13a808da65775f22cbf47862c4e5898d8f4ca1"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # eventually this should be a version=<some version> this commit
  # is on the master branch
  branch = "v0.0.7"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"
